#!/bin/sh
# NOTE(tmorris) Stop accidental commits to master.
# Inspired by:
#   http://stackoverflow.com/questions/7923505/how-to-use-git-hook-pre-commit-to-stop-commits-to-master
if [ $(git symbolic-ref HEAD 2>/dev/null) == "refs/heads/master" ]
then
   echo "Error: Cannot commit directly to 'master'."
   echo "  Bypass pre-commit hooks with '--no-verify' (but, ask yourself, WHY?!?)."
   exit 1
fi


# NOTE(tmorris) The rest copied from the sample that ships with git.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
        # Note that the use of brackets around a tr range is ok here, (it's
        # even required, for portability to Solaris 10's /usr/bin/tr), since
        # the square bracket bytes happen to fall in the designated range.
        test $(git diff --cached --name-only --diff-filter=A -z $against |
          LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
        echo "Error: Attempt to add a non-ascii file name."
        echo
        echo "If you know what you are doing you can disable this"
        echo "check using:"
        echo
        echo "  git config hooks.allownonascii true"
        echo "  --OR-- specify '--no-verify' with 'git commit'"
        echo
        exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
